import { AlertTriangle, Info } from "lucide-react";

interface DisclaimerBannerProps {
  /** When "immediate" or "soon", renders as a highlighted orange callout. */
  urgency?: "immediate" | "soon" | "schedule" | "monitor" | string;
}

const DISCLAIMER_TEXT =
  "This is a symptom assessment generated by AI, not a professional mechanical inspection. Wrenchli is not a licensed mechanic or repair facility. Always have a qualified technician inspect your vehicle before making repair decisions.";

export default function DisclaimerBanner({ urgency }: DisclaimerBannerProps) {
  const isHighUrgency = urgency === "immediate" || urgency === "soon";

  if (isHighUrgency) {
    return (
      <div
        role="alert"
        aria-live="polite"
        className="rounded-lg border-2 p-4 md:p-5 mb-6 shadow-sm"
        style={{
          backgroundColor: "hsl(var(--accent) / 0.12)",
          borderColor: "hsl(var(--accent))",
        }}
      >
        <div className="flex gap-3">
          <AlertTriangle
            className="h-6 w-6 shrink-0 mt-0.5"
            style={{ color: "hsl(var(--accent))" }}
            aria-hidden="true"
          />
          <div className="text-sm md:text-base leading-relaxed text-foreground">
            <span className="font-bold uppercase tracking-wide" style={{ color: "hsl(var(--accent))" }}>
              Safety notice:
            </span>{" "}
            {DISCLAIMER_TEXT}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      role="note"
      className="rounded-lg border-l-4 p-4 md:p-5 mb-6"
      style={{
        backgroundColor: "hsl(45 100% 97%)",
        borderLeftColor: "hsl(38 92% 50%)",
      }}
    >
      <div className="flex gap-3">
        <Info className="h-5 w-5 shrink-0 mt-0.5" style={{ color: "hsl(38 92% 50%)" }} aria-hidden="true" />
        <div className="text-sm leading-relaxed text-foreground">
          <span className="font-bold">Important disclaimer:</span> {DISCLAIMER_TEXT}
        </div>
      </div>
    </div>
  );
}
