import { type ServiceProvider, BASE_URL } from "./types.ts";

const b = BASE_URL;

export function getProvidersDatabase(): ServiceProvider[] {
  return [
    // Warren 48091
    {
      id: "warren_precision",
      name: "Precision Auto Repair",
      rating: 4.7,
      review_count: 143,
      address: "123 Main St, Warren, MI 48091",
      phone: "(586) 555-0123",
      distance_miles: 0,
      specialties: ["general", "engine", "brakes", "transmission"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=warren_precision`,
    },
    {
      id: "warren_auto_tech",
      name: "Auto Technology Inc",
      rating: 4.5,
      review_count: 89,
      address: "456 Van Dyke Ave, Warren, MI 48091",
      phone: "(586) 353-5700",
      distance_miles: 2,
      specialties: ["general", "domestic", "import"],
      price_tier: "mid",
      response_time: "4 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=warren_auto_tech`,
    },
    // Birmingham 48009
    {
      id: "birmingham_auto_europe",
      name: "Auto Europe",
      rating: 4.9,
      review_count: 156,
      address: "677 S Eton St, Birmingham, MI 48009",
      phone: "(248) 645-6300",
      distance_miles: 0,
      specialties: ["european", "luxury", "bmw", "mercedes", "audi"],
      price_tier: "premium",
      response_time: "1 hour",
      availability: "next_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=birmingham_auto_europe`,
    },
    {
      id: "birmingham_first_call",
      name: "First Call Auto",
      rating: 4.6,
      review_count: 78,
      address: "890 Maple Rd, Birmingham, MI 48009",
      phone: "(248) 555-0789",
      distance_miles: 1,
      specialties: ["european", "domestic", "general"],
      price_tier: "premium",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=birmingham_first_call`,
    },
    // Troy 48084
    {
      id: "troy_auto_pro",
      name: "Auto Pro",
      rating: 4.8,
      review_count: 234,
      address: "1234 Big Beaver Rd, Troy, MI 48084",
      phone: "(248) 555-0456",
      distance_miles: 0,
      specialties: ["general", "brakes", "electrical", "ac_service"],
      price_tier: "mid",
      response_time: "1 hour",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=troy_auto_pro`,
    },
    {
      id: "troy_auto_lab",
      name: "Auto Lab",
      rating: 4.4,
      review_count: 167,
      address: "5678 Rochester Rd, Troy, MI 48084",
      phone: "(248) 555-0321",
      distance_miles: 2,
      specialties: ["general", "oil_change", "brakes", "transmission"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=troy_auto_lab`,
    },
    // Sterling Heights 48315
    {
      id: "sterling_family_auto",
      name: "Sterling Family Auto Care",
      rating: 4.6,
      review_count: 198,
      address: "9012 Van Dyke Ave, Sterling Heights, MI 48315",
      phone: "(586) 555-0654",
      distance_miles: 0,
      specialties: ["general", "family_service", "brakes", "maintenance"],
      price_tier: "mid",
      response_time: "3 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=sterling_family_auto`,
    },
    // Ann Arbor 48104
    {
      id: "annarbor_student_auto",
      name: "A2 Student Auto Service",
      rating: 4.3,
      review_count: 156,
      address: "3456 Washtenaw Ave, Ann Arbor, MI 48104",
      phone: "(734) 555-0987",
      distance_miles: 0,
      specialties: ["general", "budget_friendly", "student_specials"],
      price_tier: "budget",
      response_time: "4 hours",
      availability: "next_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=annarbor_student_auto`,
    },
    {
      id: "annarbor_professional_auto",
      name: "Ann Arbor Professional Auto",
      rating: 4.7,
      review_count: 89,
      address: "7890 Plymouth Rd, Ann Arbor, MI 48104",
      phone: "(734) 555-0147",
      distance_miles: 3,
      specialties: ["general", "import", "luxury"],
      price_tier: "premium",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=annarbor_professional_auto`,
    },
    // Dearborn 48124
    {
      id: "dearborn_motor_city_auto",
      name: "Motor City Auto Works",
      rating: 4.8,
      review_count: 212,
      address: "2345 Michigan Ave, Dearborn, MI 48124",
      phone: "(313) 555-0234",
      distance_miles: 0,
      specialties: ["general", "domestic", "engine", "transmission"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=dearborn_motor_city_auto`,
    },
    {
      id: "dearborn_ford_country",
      name: "Ford Country Service Center",
      rating: 4.6,
      review_count: 178,
      address: "4567 Ford Rd, Dearborn, MI 48124",
      phone: "(313) 555-0567",
      distance_miles: 1,
      specialties: ["domestic", "ford", "general", "electrical"],
      price_tier: "mid",
      response_time: "3 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=dearborn_ford_country`,
    },
    {
      id: "dearborn_value_auto",
      name: "Value Auto Repair",
      rating: 4.4,
      review_count: 134,
      address: "6789 Telegraph Rd, Dearborn, MI 48124",
      phone: "(313) 555-0891",
      distance_miles: 2,
      specialties: ["general", "brakes", "oil_change", "budget_friendly"],
      price_tier: "budget",
      response_time: "4 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=dearborn_value_auto`,
    },
    // Livonia 48150
    {
      id: "livonia_suburban_auto",
      name: "Suburban Auto Care",
      rating: 4.7,
      review_count: 189,
      address: "12345 Middlebelt Rd, Livonia, MI 48150",
      phone: "(734) 555-0345",
      distance_miles: 0,
      specialties: ["general", "family_service", "brakes", "maintenance"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=livonia_suburban_auto`,
    },
    {
      id: "livonia_euro_tech",
      name: "Euro Tech Auto Specialists",
      rating: 4.8,
      review_count: 145,
      address: "23456 Plymouth Rd, Livonia, MI 48150",
      phone: "(734) 555-0678",
      distance_miles: 2,
      specialties: ["european", "luxury", "bmw", "mercedes", "volkswagen"],
      price_tier: "premium",
      response_time: "1 hour",
      availability: "next_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=livonia_euro_tech`,
    },
    {
      id: "livonia_quick_lane",
      name: "Quick Lane Livonia",
      rating: 4.3,
      review_count: 267,
      address: "34567 Seven Mile Rd, Livonia, MI 48150",
      phone: "(734) 555-0912",
      distance_miles: 3,
      specialties: ["general", "oil_change", "tires", "budget_friendly"],
      price_tier: "budget",
      response_time: "1 hour",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=livonia_quick_lane`,
    },
    // Detroit 48201
    {
      id: "detroit_downtown_auto",
      name: "Downtown Detroit Auto Service",
      rating: 4.7,
      review_count: 245,
      address: "1200 Woodward Ave, Detroit, MI 48201",
      phone: "(313) 555-1200",
      distance_miles: 0,
      specialties: ["general", "domestic", "engine", "electrical"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=detroit_downtown_auto`,
    },
    {
      id: "detroit_cass_corridor_auto",
      name: "Cass Corridor Auto Repair",
      rating: 4.5,
      review_count: 178,
      address: "4500 Cass Ave, Detroit, MI 48201",
      phone: "(313) 555-4500",
      distance_miles: 1,
      specialties: ["general", "brakes", "suspension", "budget_friendly"],
      price_tier: "budget",
      response_time: "3 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=detroit_cass_corridor_auto`,
    },
    {
      id: "detroit_midtown_motors",
      name: "Midtown Motors",
      rating: 4.8,
      review_count: 134,
      address: "3456 Second Ave, Detroit, MI 48201",
      phone: "(313) 555-3456",
      distance_miles: 2,
      specialties: ["european", "luxury", "import", "hybrid"],
      price_tier: "premium",
      response_time: "1 hour",
      availability: "next_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=detroit_midtown_motors`,
    },
    // Southfield 48075
    {
      id: "southfield_telegraph_auto",
      name: "Telegraph Auto Care",
      rating: 4.6,
      review_count: 203,
      address: "20100 Telegraph Rd, Southfield, MI 48075",
      phone: "(248) 555-2010",
      distance_miles: 0,
      specialties: ["general", "domestic", "brakes", "transmission"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=southfield_telegraph_auto`,
    },
    {
      id: "southfield_greenfield_auto",
      name: "Greenfield Import Specialists",
      rating: 4.9,
      review_count: 167,
      address: "25000 Greenfield Rd, Southfield, MI 48075",
      phone: "(248) 555-2500",
      distance_miles: 2,
      specialties: ["european", "luxury", "bmw", "mercedes", "audi", "import"],
      price_tier: "premium",
      response_time: "1 hour",
      availability: "next_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=southfield_greenfield_auto`,
    },
    {
      id: "southfield_budget_brake",
      name: "Budget Brake & Auto",
      rating: 4.3,
      review_count: 289,
      address: "29000 Northwestern Hwy, Southfield, MI 48075",
      phone: "(248) 555-2900",
      distance_miles: 3,
      specialties: ["general", "brakes", "oil_change", "tires", "budget_friendly"],
      price_tier: "budget",
      response_time: "1 hour",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=southfield_budget_brake`,
    },
    // Royal Oak 48067
    {
      id: "royaloak_main_street_auto",
      name: "Main Street Auto Repair",
      rating: 4.7,
      review_count: 198,
      address: "500 N Main St, Royal Oak, MI 48067",
      phone: "(248) 555-0500",
      distance_miles: 0,
      specialties: ["general", "domestic", "brakes", "electrical"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=royaloak_main_street_auto`,
    },
    {
      id: "royaloak_euro_auto",
      name: "Royal Oak Euro Auto",
      rating: 4.8,
      review_count: 134,
      address: "1200 E 11 Mile Rd, Royal Oak, MI 48067",
      phone: "(248) 555-1200",
      distance_miles: 1,
      specialties: ["european", "luxury", "bmw", "mercedes", "volkswagen"],
      price_tier: "premium",
      response_time: "1 hour",
      availability: "next_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=royaloak_euro_auto`,
    },
    {
      id: "royaloak_quick_fix",
      name: "Quick Fix Auto Royal Oak",
      rating: 4.4,
      review_count: 312,
      address: "2800 N Woodward Ave, Royal Oak, MI 48067",
      phone: "(248) 555-2800",
      distance_miles: 2,
      specialties: ["general", "oil_change", "tires", "budget_friendly"],
      price_tier: "budget",
      response_time: "1 hour",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=royaloak_quick_fix`,
    },
    // Farmington Hills 48334
    {
      id: "farmhills_orchard_auto",
      name: "Orchard Lake Auto Service",
      rating: 4.7,
      review_count: 223,
      address: "30100 Orchard Lake Rd, Farmington Hills, MI 48334",
      phone: "(248) 555-3010",
      distance_miles: 0,
      specialties: ["general", "domestic", "engine", "transmission"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=farmhills_orchard_auto`,
    },
    {
      id: "farmhills_grand_river_auto",
      name: "Grand River Import Specialists",
      rating: 4.9,
      review_count: 156,
      address: "33000 Grand River Ave, Farmington Hills, MI 48334",
      phone: "(248) 555-3300",
      distance_miles: 2,
      specialties: ["european", "luxury", "import", "bmw", "audi"],
      price_tier: "premium",
      response_time: "1 hour",
      availability: "next_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=farmhills_grand_river_auto`,
    },
    {
      id: "farmhills_value_tire",
      name: "Value Tire & Auto",
      rating: 4.3,
      review_count: 278,
      address: "28500 Northwestern Hwy, Farmington Hills, MI 48334",
      phone: "(248) 555-2850",
      distance_miles: 3,
      specialties: ["general", "tires", "oil_change", "brakes", "budget_friendly"],
      price_tier: "budget",
      response_time: "1 hour",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=farmhills_value_tire`,
    },
    // Novi 48375
    {
      id: "novi_twelve_oaks_auto",
      name: "Twelve Oaks Auto Care",
      rating: 4.7,
      review_count: 215,
      address: "42000 Grand River Ave, Novi, MI 48375",
      phone: "(248) 555-4200",
      distance_miles: 0,
      specialties: ["general", "domestic", "brakes", "engine"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=novi_twelve_oaks_auto`,
    },
    {
      id: "novi_luxury_auto",
      name: "Novi Luxury Auto Specialists",
      rating: 4.9,
      review_count: 142,
      address: "39500 Ten Mile Rd, Novi, MI 48375",
      phone: "(248) 555-3950",
      distance_miles: 2,
      specialties: ["european", "luxury", "bmw", "mercedes", "audi", "land_rover"],
      price_tier: "premium",
      response_time: "1 hour",
      availability: "next_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=novi_luxury_auto`,
    },
    {
      id: "novi_express_lube",
      name: "Express Lube & Auto Novi",
      rating: 4.4,
      review_count: 334,
      address: "44000 West Rd, Novi, MI 48375",
      phone: "(248) 555-4400",
      distance_miles: 3,
      specialties: ["general", "oil_change", "tires", "budget_friendly"],
      price_tier: "budget",
      response_time: "1 hour",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=novi_express_lube`,
    },
    // Canton 48187
    {
      id: "canton_michigan_ave_auto",
      name: "Michigan Ave Auto Works",
      rating: 4.6,
      review_count: 198,
      address: "41500 Michigan Ave, Canton, MI 48187",
      phone: "(734) 555-4150",
      distance_miles: 0,
      specialties: ["general", "domestic", "transmission", "brakes"],
      price_tier: "mid",
      response_time: "2 hours",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=canton_michigan_ave_auto`,
    },
    {
      id: "canton_euro_precision",
      name: "Euro Precision Canton",
      rating: 4.8,
      review_count: 123,
      address: "45000 Ford Rd, Canton, MI 48187",
      phone: "(734) 555-4500",
      distance_miles: 2,
      specialties: ["european", "luxury", "import", "bmw", "volkswagen"],
      price_tier: "premium",
      response_time: "1 hour",
      availability: "next_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=canton_euro_precision`,
    },
    {
      id: "canton_budget_auto",
      name: "Canton Budget Auto Center",
      rating: 4.3,
      review_count: 267,
      address: "42700 Cherry Hill Rd, Canton, MI 48187",
      phone: "(734) 555-4270",
      distance_miles: 3,
      specialties: ["general", "oil_change", "brakes", "tires", "budget_friendly"],
      price_tier: "budget",
      response_time: "1 hour",
      availability: "same_day",
      wrenchli_verified: true,
      quote_url: `${b}/vehicle-insights?shop=canton_budget_auto`,
    },
  ];
}
