import jsPDF from "jspdf";
import wrenchliLogo from "@/assets/wrenchli-logo.jpeg";

export async function exportDiagnosisPdf(content: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const usableWidth = pageWidth - margin * 2;

  // Load and add logo
  try {
    const img = new Image();
    img.crossOrigin = "anonymous";
    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve();
      img.onerror = reject;
      img.src = wrenchliLogo;
    });
    const logoW = 30;
    const logoH = (img.naturalHeight / img.naturalWidth) * logoW;
    doc.addImage(img, "JPEG", margin, 12, logoW, logoH);
  } catch {
    // fallback: text logo
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Wrenchli", margin, 22);
  }

  // Header text
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("AI Vehicle Diagnosis Report", pageWidth - margin, 18, { align: "right" });
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), pageWidth - margin, 24, { align: "right" });

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, 34, pageWidth - margin, 34);

  // Body content - strip markdown formatting for cleaner PDF
  const cleaned = content
    .replace(/#{1,3}\s/g, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`(.*?)`/g, "$1");

  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "normal");

  const lines = doc.splitTextToSize(cleaned, usableWidth);
  let y = 42;
  const lineHeight = 5.5;
  const pageHeight = doc.internal.pageSize.getHeight();

  for (const line of lines) {
    if (y + lineHeight > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  }

  // Footer
  const footerY = pageHeight - 10;
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text("Generated by Wrenchli — wrenchli.com", pageWidth / 2, footerY, { align: "center" });
  doc.text("For informational purposes only. Not a substitute for professional inspection.", pageWidth / 2, footerY + 4, { align: "center" });

  doc.save(`wrenchli-diagnosis-${Date.now()}.pdf`);
}
