DROP TABLE IF EXISTS public.spotlight_technician_endorsements CASCADE;
DROP TABLE IF EXISTS public.spotlight_technicians CASCADE;
DROP TABLE IF EXISTS public.spotlight_shops CASCADE;

CREATE TABLE public.spotlight_shops (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  address_line1 TEXT,
  city TEXT NOT NULL DEFAULT 'Detroit',
  state TEXT NOT NULL DEFAULT 'MI',
  zip TEXT,
  phone TEXT,
  website_url TEXT,
  hours_json JSONB,
  specialties TEXT[] NOT NULL DEFAULT '{}',
  description TEXT,
  google_rating NUMERIC(2,1),
  google_review_count INTEGER,
  listing_status TEXT NOT NULL DEFAULT 'unclaimed'
    CHECK (listing_status IN ('unclaimed', 'claimed', 'partner')),
  verified_at TIMESTAMPTZ,
  verified_by TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.spotlight_technicians (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id UUID NOT NULL REFERENCES public.spotlight_shops(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  photo_url TEXT,
  bio TEXT,
  specialties TEXT[] NOT NULL DEFAULT '{}',
  years_experience INTEGER,
  ase_certifications TEXT[] NOT NULL DEFAULT '{}',
  mi_cert_number TEXT,
  mi_cert_verified BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'shop_added'
    CHECK (status IN ('shop_added', 'verified')),
  wrenchli_job_count INTEGER,
  wrenchli_rating_avg NUMERIC(2,1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.spotlight_technician_endorsements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  technician_id UUID NOT NULL REFERENCES public.spotlight_technicians(id) ON DELETE CASCADE,
  consumer_ref TEXT NOT NULL,
  job_reference TEXT,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT ON public.spotlight_shops TO anon, authenticated;
GRANT SELECT ON public.spotlight_technicians TO anon, authenticated;
GRANT SELECT ON public.spotlight_technician_endorsements TO anon, authenticated;
GRANT ALL ON public.spotlight_shops TO service_role;
GRANT ALL ON public.spotlight_technicians TO service_role;
GRANT ALL ON public.spotlight_technician_endorsements TO service_role;

ALTER TABLE public.spotlight_shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spotlight_technicians ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spotlight_technician_endorsements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read spotlight shops"
  ON public.spotlight_shops FOR SELECT USING (true);
CREATE POLICY "Public can read spotlight technicians"
  ON public.spotlight_technicians FOR SELECT USING (true);
CREATE POLICY "Public can read spotlight technician endorsements"
  ON public.spotlight_technician_endorsements FOR SELECT USING (true);

CREATE INDEX idx_spotlight_shops_slug ON public.spotlight_shops (slug);
CREATE INDEX idx_spotlight_shops_status ON public.spotlight_shops (listing_status);
CREATE INDEX idx_spotlight_technicians_shop ON public.spotlight_technicians (shop_id);
CREATE INDEX idx_spotlight_endorsements_tech ON public.spotlight_technician_endorsements (technician_id);

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('unique-auto-repair-and-tire', 'Unique Auto Repair and Tire', '15327 Joy Rd', 'Detroit', 'MI', '48228', '(313) 945-7661', 'https://uniqueautorepairandtire.com/', '{"friday": "08:00-17:00", "monday": "08:00-17:00", "saturday": "08:00-14:30", "sunday": null, "thursday": "08:00-17:00", "tuesday": "08:00-17:00", "wednesday": "08:00-17:00"}'::jsonb, '{"general repair","tires","oil change","transmission","mufflers","brakes","maintenance"}', 'Family-owned and operated Joy Road shop with over 35 years of experience offering complete auto repair, tires, and maintenance for foreign and domestic vehicles.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://uniqueautorepairandtire.com/|https://www.surecritic.com/reviews/unique-auto-repair-inc?review_id=10840528|SureCritic 4.9/549 is not a Google rating; directories conflict on weekday close (5pm vs 6pm) and Saturday hours — official-profile hours used.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('midtown-auto-pros', 'Midtown Auto Pros', '3902 Cass Ave', 'Detroit', 'MI', '48201', '(313) 831-1111', 'http://www.midtownautopros.com/', '{"friday": "09:00-18:00", "monday": "09:00-18:00", "saturday": "09:00-17:00", "sunday": null, "thursday": "09:00-18:00", "tuesday": "09:00-18:00", "wednesday": "09:00-18:00"}'::jsonb, '{"tires","wheel alignment","general repair","oil change","brake inspection","towing"}', 'Independent Midtown auto service shop offering tires, general repair, and towing, advertising discounts for students and hospital staff.', '4.3', '20', 'unclaimed', '2026-09-18', 'research', 'http://www.midtownautopros.com/|https://autorepairscore.com/mi/detroit/midtown-auto-detroit-michigan|AutoRepairScore explicitly attributes the 4.3/20 rating to Google; Birdeye profile names it ''Midtown auto''.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('moe-town-auto-repair', 'Moe Town Auto Repair', '15752 W Warren Ave', 'Detroit', 'MI', '48228', NULL, NULL, NULL, '{"general repair"}', 'Independent auto repair shop on West Warren Avenue offering complete auto repair.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://www.mapquest.com/us/michigan/moe-town-387900586|Phone conflicts between directories — (313) 888-5560 vs (313) 395-2800 — left null; hours conflict across sources — left null; Birdeye directory rating 4.3/158 is not established as Google.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('motech-automotive-w-warren', 'Motech Automotive', '15651 W Warren Ave', 'Detroit', 'MI', '48228', '(313) 846-5047', 'https://www.motech1.com', '{"friday": "08:30-18:00", "monday": "08:30-18:00", "saturday": "09:00-17:00", "sunday": null, "thursday": "08:30-18:00", "tuesday": "08:30-18:00", "wednesday": "08:30-18:00"}'::jsonb, '{"general repair","electrical diagnostics","engine repair","brakes","tires","exhaust"}', 'Independent automotive repair and diagnostics shop on West Warren run by an ASE-certified master technician specializing in electrical and computer work.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://www.motech1.com|https://www.yellowpages.com/detroit-mi/mip/motech-automotive-458622258|Official site lists Sunday closed; some directories show Sunday hours. Distinct website from the Greenfield Rd Motech location — relationship flagged for confirmation.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('motech-automotive-greenfield', 'Motech Automotive (Greenfield)', '14644 Greenfield Rd', 'Detroit', 'MI', '48227', '(313) 444-1188', 'https://motechautomotive.com/', '{"friday": "08:30-18:00", "monday": "08:30-18:00", "saturday": "08:30-15:30", "sunday": null, "thursday": "08:30-18:00", "tuesday": "08:30-18:00", "wednesday": "08:30-18:00"}'::jsonb, '{"general repair","oil change","brakes","engine repair"}', 'Independent neighborhood auto repair shop on Greenfield Road staffed by ASE-certified mechanics, offering oil changes, brakes, and engine repairs.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://motechautomotive.com/|https://maps.roadtrippers.com/us/detroit-mi/services/motech-automotive-detroit-mi--0|Saturday open varies 9:00 vs 8:30 across sources. Relationship to the W Warren Motech (motech1.com) flagged for confirmation — distinct sites/phones kept as separate listings.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('rhino-mobile-mechanics', 'Rhino Mobile Mechanics', '1532 Adelaide St', 'Detroit', 'MI', '48207', '(313) 513-0820', 'https://www.detroitmobilemechanics.com/', '{"friday": "09:00-20:00", "monday": "09:00-20:00", "saturday": "10:00-19:00", "sunday": "10:00-19:00", "thursday": "09:00-20:00", "tuesday": "09:00-20:00", "wednesday": "09:00-20:00"}'::jsonb, '{"mobile mechanic","pre-purchase inspections","brakes","cooling systems","belts","general repair"}', 'Mobile mechanic service based in Detroit that travels to customers for repairs, pre-purchase inspections, and emergency service seven days a week.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://www.detroitmobilemechanics.com/|https://www.detroitmobilemechanics.com/pre-purchase-inspection/|Mobile-only service; no public storefront — listed as a mobile option, not a fixed shop.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('moes-advanced-tech-auto-repair', 'Moe''s Advanced Tech Auto Repair Inc', '14298 E 7 Mile Rd', 'Detroit', 'MI', '48205', '(313) 527-2000', 'https://moes-advanced-tech-auto-repair-inc.business.site/', '{"friday": "09:00-17:30", "monday": "09:00-17:30", "saturday": "09:00-15:00", "sunday": null, "thursday": "09:00-17:30", "tuesday": "09:00-17:30", "wednesday": "09:00-17:30"}'::jsonb, '{"general repair","auto body","engine repair","maintenance"}', 'Independent general auto repair and body shop on East Seven Mile offering mechanical and collision repair with regular customer updates.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://moes-advanced-tech-auto-repair-inc.business.site/|https://reviews.birdeye.com/moes-advanced-tech-auto-repair-inc-156041129106360|https://www.loc8nearme.com/michigan/detroit/moes-advanced-tech-auto-repair-inc/5358851/|Reviews are mixed; business is active with a BBB profile (est. 2019).');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('sheba-auto-services-and-sales', 'Sheba Auto Services and Sales', '9000 W Vernor Hwy', 'Detroit', 'MI', '48209', '(313) 586-1026', NULL, '{"friday": "09:00-18:00", "monday": "09:00-18:00", "saturday": "10:00-16:00", "sunday": null, "thursday": "09:00-18:00", "tuesday": "09:00-18:00", "wednesday": "09:00-18:00"}'::jsonb, '{"general repair","used car sales","maintenance"}', 'Independent auto services and vehicle sales business on West Vernor Highway.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://maps.roadtrippers.com/us/detroit-mi/services/sheba-auto-services-and-sales|https://reviews.birdeye.com/sheba-auto-services-sales-165335459447280|Birdeye 4.5/15 is not established as Google; no official website found.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('southwest-customs-llc', 'Southwest Customs LLC', '4201 Toledo St', 'Detroit', 'MI', '48209', '(313) 969-4928', NULL, '{"friday": "09:00-18:00", "monday": "09:00-18:00", "saturday": "09:00-16:30", "sunday": null, "thursday": "09:00-18:00", "tuesday": "09:00-18:00", "wednesday": "09:00-18:00"}'::jsonb, '{"general repair","custom work","maintenance"}', 'Independent automotive shop on Toledo Street in Southwest Detroit offering repair and custom work.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://www.instagram.com/explore/locations/169434449593381|https://reviews.birdeye.com/southwest-customs-llc-171697902778020|Saturday hours approximate (4:00 vs 4:30 across sources); no official website found.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('detroit-oil-express', 'Detroit Oil Express', '17415 Livernois Ave', 'Detroit', 'MI', '48221', '(313) 270-0570', NULL, '{"friday": "08:00-19:00", "monday": "08:00-18:00", "saturday": "08:00-18:00", "sunday": null, "thursday": "08:00-19:00", "tuesday": "08:00-18:00", "wednesday": "08:00-18:00"}'::jsonb, '{"oil change","lube services","maintenance"}', 'Independent quick-lube shop on Livernois Avenue offering oil changes and basic maintenance.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://reviews.birdeye.com/detroit-oil-express-156067343174512|https://www.loc8nearme.com/michigan/detroit/detroit-oil-express/4394574/|Directory rating provenance conflicts — no Google fields set.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('carline-complete-auto-repair-collision', 'CarLine Complete Auto Repair & Collision', '8118 Livernois Ave', 'Detroit', 'MI', '48204', '(313) 355-4439', 'https://www.carlineautomi.com', NULL, '{"general repair","collision repair","auto body","maintenance"}', 'Independent shop on Livernois Avenue offering complete auto repair and collision services.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://www.yellowpages.com/detroit-mi/mip/carline-complete-auto-repair-collision-534907951?lid=1002194166140|https://www.loc8nearme.com/michigan/detroit/car-line-auto-repair/4391131/|Phone conflict — (313) 355-4439 appears current, (313) 894-5723 is legacy; hours not verified — left null.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('fred-sons-1-collision', 'Fred & Sons #1 Collision', '17600 Livernois Ave', 'Detroit', 'MI', '48221', '(313) 863-9000', NULL, '{"friday": "08:30-17:00", "monday": "08:30-17:00", "saturday": null, "sunday": null, "thursday": "08:30-17:00", "tuesday": "08:30-17:00", "wednesday": "08:30-17:00"}'::jsonb, '{"collision repair","auto body","paint"}', 'Independent collision repair shop on Livernois Avenue offering auto body work.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://www.loc8nearme.com/michigan/detroit/fred-and-sons-collision/5438194/|https://reviews.birdeye.com/fred-sons-collision-156052344719454|Birdeye 3.7/66 is not proven Google; no official website found.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('corktown-collision', 'Corktown Collision', '5239 Trumbull St', 'Detroit', 'MI', '48208', '(313) 896-6666', 'http://www.corktowncollision.com/', '{"friday": "10:00-17:00", "monday": "10:00-17:00", "saturday": null, "sunday": null, "thursday": "10:00-17:00", "tuesday": "10:00-17:00", "wednesday": "10:00-17:00"}'::jsonb, '{"collision repair","auto body"}', 'Independent auto body and collision shop in Corktown.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'http://www.corktowncollision.com/|https://www.waze.com/live-map/directions/us/mi/detroit/corktown-collision?to=place.ChIJoV6v9FjNJIgRBsMfVwucFEE|Saturday hours conflict between sources (3pm vs 5pm) — left null.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('gratiot-auto-repair', 'Gratiot Auto Repair', '13990 Gratiot Ave', 'Detroit', 'MI', '48205', '(313) 245-4545', NULL, '{"friday": "08:30-18:00", "monday": "08:30-18:00", "saturday": "08:30-18:00", "sunday": null, "thursday": "08:30-18:00", "tuesday": "08:30-18:00", "wednesday": "08:30-18:00"}'::jsonb, '{"general repair","maintenance"}', 'Independent general auto repair shop on Gratiot Avenue.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://meta.ai?place_id=1202011157033433|https://maps.roadtrippers.com/us/detroit-mi/services/gratiot-auto-repair-detroit-mi--0|No official website found.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('detroit-auto-repair-center-1', 'Detroit Auto Repair Center #1', '18500 Wyoming Ave', 'Detroit', 'MI', '48221', '(313) 340-1100', 'http://www.detroitautorepaircenter.com/', '{"friday": "08:30-18:00", "monday": "08:30-18:00", "saturday": null, "sunday": null, "thursday": "08:30-18:00", "tuesday": "08:30-18:00", "wednesday": "08:30-18:00"}'::jsonb, '{"general repair","maintenance"}', 'Independent general auto repair shop on Wyoming Avenue.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'http://www.detroitautorepaircenter.com/|https://location.com/categories/automotive-and-vehicles/us/mi/detroit/detroit-auto-repair-3706490979|Certified profile hours Mon–Fri 8:30–6 used.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('detroit-express-muffler', 'Detroit Express Muffler', '15430 Fenkell Ave', 'Detroit', 'MI', '48227', '(313) 836-9390', 'http://detroitexpressmuffler.com/', '{"friday": "08:00-18:00", "monday": "08:00-18:00", "saturday": "08:00-16:00", "sunday": null, "thursday": "08:00-18:00", "tuesday": "08:00-18:00", "wednesday": "08:00-18:00"}'::jsonb, '{"exhaust","mufflers","oil change","maintenance"}', 'Independent muffler and exhaust shop on Fenkell Avenue offering exhaust work and oil changes.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'http://detroitexpressmuffler.com/|https://gmg-wdiv-prod.cdn.arcpublishing.com/news/local/2026/05/26/detroit-auto-shop-offers-free-oil-changes-to-help-drivers-save-money/|Local WDIV coverage (May 2026) corroborates active operation.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('oil-lube-zone', 'Oil & Lube Zone', '10700 W Seven Mile Rd #1920', 'Detroit', 'MI', '48221', '(313) 340-9299', 'https://oil-lube-zone.business.site/', '{"friday": "08:00-19:00", "monday": "08:00-18:00", "saturday": null, "sunday": null, "thursday": "08:00-19:00", "tuesday": "08:00-18:00", "wednesday": "08:00-18:00"}'::jsonb, '{"oil change","lube services","maintenance"}', 'Independent oil change and lube shop on West Seven Mile Road.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://oil-lube-zone.business.site/|https://www.loc8nearme.com/michigan/detroit/oil-and-lube-zone/8440385/|Saturday hours conflict between sources (6pm vs 7pm) — left null.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('a-tech-auto-clinic', 'A Tech Auto Clinic', '11300 Greenfield Rd', 'Detroit', 'MI', '48227', '(313) 838-8822', NULL, '{"friday": "08:00-17:00", "monday": "08:00-17:00", "saturday": "08:00-15:00", "sunday": null, "thursday": "08:00-17:00", "tuesday": "08:00-17:00", "wednesday": "08:00-17:00"}'::jsonb, '{"general repair","maintenance"}', 'Independent general auto repair shop on Greenfield Road.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://reviews.birdeye.com/a-tech-auto-clinic-156044665407660|https://www.loc8nearme.com/michigan/detroit/a-tech-auto-clinic/8883565/|Saturday hours conflict (3pm vs 4pm) — Birdeye hours used; a search result''s linked ''official'' domain appeared unrelated and is not used.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('simons-auto-repair', 'Simons Auto Repair', '5531 E McNichols Rd', 'Detroit', 'MI', '48212', '(313) 366-8122', 'https://www.simonsautorepairshop.com/', NULL, '{"general repair","maintenance"}', 'Independent general auto repair shop on East McNichols Road.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://www.simonsautorepairshop.com/|https://www.loc8nearme.com/michigan/detroit/simons-auto-repair/4622452/|Official-profile hours differ from directories — left null pending confirmation.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('detroit-tire-king', 'Detroit Tire King', '9000 Conner St', 'Detroit', 'MI', '48213', '(313) 949-4870', NULL, '{"friday": "08:30-18:00", "monday": "08:30-18:00", "saturday": null, "sunday": null, "thursday": "08:30-18:00", "tuesday": "08:30-18:00", "wednesday": "08:30-18:00"}'::jsonb, '{"tires","tire installation","balancing","TPMS resets"}', 'Independent tire shop on Conner Street offering tire installation with mounting, balancing, valve stems, tire disposal, and TPMS resets.', '4.1', '156', 'unclaimed', '2026-09-18', 'research', 'https://simpletire.com/tire-shops/shop/detroit-tire-king/84355|https://reviews.birdeye.com/detroit-tire-king-169863641893858|Birdeye''s rating breakdown explicitly attributes all 156 reviews to Google; Birdeye FAQ (61 days ago) said ''temporarily closed'' but Birdeye''s category page (38 days ago) shows Open and SimpleTire (8 days ago) lists current hours — treated as open, flagged.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('super-auto-glass', 'Super Auto Glass', '10152 E Warren Ave', 'Detroit', 'MI', '48214', '(313) 571-8000', 'http://www.super-autoglass.com/', '{"friday": "09:00-17:00", "monday": "09:00-17:00", "saturday": "08:30-14:00", "sunday": null, "thursday": "09:00-17:00", "tuesday": "09:00-17:00", "wednesday": "09:00-17:00"}'::jsonb, '{"windshields","auto glass","glass repair","mirror replacement","window repair","tinting"}', 'Independent auto glass shop on East Warren Avenue offering windshield replacement and repair with a lifetime guarantee against leaking windshields.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'http://www.super-autoglass.com/|https://reviews.birdeye.com/super-auto-glass-156037222277938|https://www.superpages.com/detroit-mi/bpp/super-auto-glass-5710466|Superpages reports ~26 years in business; Birdeye 4.3/147 is not established as Google.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('quality-muffler-and-brakes', 'Quality Muffler and Brakes', '14646 Fenkell Ave', 'Detroit', 'MI', '48227', '(313) 646-4651', 'https://qualitymufflerbrakes.com/', '{"friday": "08:00-18:00", "monday": "08:00-18:00", "saturday": "08:00-16:00", "sunday": null, "thursday": "08:00-18:00", "tuesday": "08:00-18:00", "wednesday": "08:00-18:00"}'::jsonb, '{"brakes","mufflers","exhaust","general repair"}', 'Independent shop on Fenkell Avenue focused on brakes, mufflers, and vehicle check-ups; walk-ins welcome.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://qualitymufflerbrakes.com/|https://maps.roadtrippers.com/us/detroit-mi/services/quality-muffler-brakes-detroit|A ''Quality Muffler and Brakes'' also appears in Farmington Hills under a different domain — possible second location or unrelated business; flagged.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('all-in-1-oil-change-and-auto-repair', 'All In 1 Oil Change and Auto Repair', '4000 W McNichols Rd', 'Detroit', 'MI', '48221', '(313) 340-2820', 'http://www.allin1oilchange.com/', '{"friday": "09:00-18:00", "monday": "09:00-18:00", "saturday": "09:00-16:00", "sunday": null, "thursday": "09:00-18:00", "tuesday": "09:00-18:00", "wednesday": "09:00-18:00"}'::jsonb, '{"oil change","general repair","transmission","suspension"}', 'Independent shop on West McNichols offering oil changes and general auto repair for domestic and foreign vehicles.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'http://www.allin1oilchange.com/|https://www.loc8nearme.com/michigan/detroit/all-in-1-oil-change-and-auto-repair-domestic-and-foreign/4387887/|Reviews mention additional branches (e.g., Redford) — possible small local chain; flagged.');

INSERT INTO public.spotlight_shops (slug, name, address_line1, city, state, zip, phone, website_url, hours_json, specialties, description, google_rating, google_review_count, listing_status, verified_at, verified_by, notes) VALUES ('motown-automotive-supercenter', 'Motown Automotive SuperCenter', '14527 Greenfield Rd', 'Detroit', 'MI', '48227', NULL, NULL, '{"friday": "08:00-18:00", "monday": "08:00-18:00", "saturday": "08:00-18:00", "sunday": null, "thursday": "08:00-18:00", "tuesday": "08:00-18:00", "wednesday": "08:00-18:00"}'::jsonb, '{"general repair","maintenance","air conditioning"}', 'Independent auto repair shop on Greenfield Road offering major and minor auto repairs and free vehicle check-ups.', NULL, NULL, 'unclaimed', '2026-09-18', 'research', 'https://business.google.com/v/motown-automotive-supercenter/015665857893737875698/82c7/_|Hours from current business profile (Mon–Sat 8–6); phone and website not verified — left null.');
